const cards =
  [{
    title: 'Animals 1',
    img: './img/horse.jpg',
    index: 0,
    isVisibleInMenu: true,
  },
  {
    title: 'Animals 2',
    img: './img/turtle.jpg',
    index: 1,
    isVisibleInMenu: true,
  },
  {
    title: 'Clothes',
    img: './img/blouse.jpg',
    index: 2,
    isVisibleInMenu: true,
  },
  {
    title: 'Emotions',
    img: './img/happy.jpg',
    index: 3,
    isVisibleInMenu: true,
  },
  {
    title: 'Vegetables',
    img: './img/pumpkin.jpg',
    index: 4,
    isVisibleInMenu: true,
  },
  {
    title: 'Fruits',
    img: './img/banana.jpg',
    index: 5,
    isVisibleInMenu: true,
  },
  {
    title: 'Nature',
    img: './img/forest.jpg',
    index: 6,
    isVisibleInMenu: true,
  },
  {
    title: 'City',
    img: './img/road.jpg',
    index: 7,
    isVisibleInMenu: true,
  },
  ];

const cards1: {
  [key: string]: string | number;
}[][] = [
  [
    {
      category: 'Animals 1',
      word: 'cat',
      translation: 'кот',
      image: './img/cat.jpg',
      audioSrc: './audio/cat.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Animals 1',
      word: 'chick',
      translation: 'цыплёнок',
      image: './img/chick.jpg',
      audioSrc: './audio/chick.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Animals 1',
      word: 'chicken',
      translation: 'курица',
      image: './img/chicken.jpg',
      audioSrc: './audio/chicken.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Animals 1',
      word: 'dog',
      translation: 'собака',
      image: './img/dog.jpg',
      audioSrc: './audio/dog.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Animals 1',
      word: 'horse',
      translation: 'лошадь',
      image: './img/horse.jpg',
      audioSrc: './audio/horse.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Animals 1',
      word: 'pig',
      translation: 'свинья',
      image: './img/pig.jpg',
      audioSrc: './audio/pig.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Animals 1',
      word: 'rabbit',
      translation: 'кролик',
      image: './img/rabbit.jpg',
      audioSrc: './audio/rabbit.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Animals 1',
      word: 'sheep',
      translation: 'овца',
      image: './img/sheep.jpg',
      audioSrc: './audio/sheep.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
  ],
  [
    {
      category: 'Animals 2',
      word: 'bird',
      translation: 'птица',
      image: './img/bird.jpg',
      audioSrc: './audio/bird.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Animals 2',
      word: 'fish',
      translation: 'рыба',
      image: './img/fish1.jpg',
      audioSrc: './audio/fish.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Animals 2',
      word: 'frog',
      translation: 'жаба',
      image: './img/frog.jpg',
      audioSrc: './audio/frog.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Animals 2',
      word: 'giraffe',
      translation: 'жирафа',
      image: './img/giraffe.jpg',
      audioSrc: './audio/giraffe.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Animals 2',
      word: 'lion',
      translation: 'лев',
      image: './img/lion.jpg',
      audioSrc: './audio/lion.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Animals 2',
      word: 'mouse',
      translation: 'мышь',
      image: './img/mouse.jpg',
      audioSrc: './audio/mouse.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Animals 2',
      word: 'turtle',
      translation: 'черепаха',
      image: './img/turtle.jpg',
      audioSrc: './audio/turtle.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Animals 2',
      word: 'dolphin',
      translation: 'дельфин',
      image: './img/dolphin.jpg',
      audioSrc: './audio/dolphin.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
  ],
  [
    {
      category: 'Clothes',
      word: 'skirt',
      translation: 'юбка',
      image: './img/skirt.jpg',
      audioSrc: './audio/skirt.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Clothes',
      word: 'pants',
      translation: 'брюки',
      image: './img/pants.jpg',
      audioSrc: './audio/pants.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Clothes',
      word: 'blouse',
      translation: 'блузка',
      image: './img/blouse.jpg',
      audioSrc: './audio/blouse.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Clothes',
      word: 'dress',
      translation: 'платье',
      image: './img/dress.jpg',
      audioSrc: './audio/dress.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Clothes',
      word: 'boot',
      translation: 'ботинок',
      image: './img/boot.jpg',
      audioSrc: './audio/boot.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Clothes',
      word: 'shirt',
      translation: 'рубашка',
      image: './img/shirt.jpg',
      audioSrc: './audio/shirt.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Clothes',
      word: 'coat',
      translation: 'пальто',
      image: './img/coat.jpg',
      audioSrc: './audio/coat.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Clothes',
      word: 'shoe',
      translation: 'туфли',
      image: './img/shoe.jpg',
      audioSrc: './audio/shoe.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
  ],
  [
    {
      category: 'Emotions',
      word: 'sad',
      translation: 'грустный',
      image: './img/sad.jpg',
      audioSrc: './audio/sad.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Emotions',
      word: 'angry',
      translation: 'сердитый',
      image: './img/angry.jpg',
      audioSrc: './audio/angry.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Emotions',
      word: 'happy',
      translation: 'счастливый',
      image: './img/happy.jpg',
      audioSrc: './audio/happy.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Emotions',
      word: 'tired',
      translation: 'уставший',
      image: './img/tired.jpg',
      audioSrc: './audio/tired.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Emotions',
      word: 'surprised',
      translation: 'удивлённый',
      image: './img/surprised.jpg',
      audioSrc: './audio/surprised.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Emotions',
      word: 'scared',
      translation: 'испуганный',
      image: './img/scared.jpg',
      audioSrc: './audio/scared.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Emotions',
      word: 'smile',
      translation: 'улыбка',
      image: './img/smile.jpg',
      audioSrc: './audio/smile.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Emotions',
      word: 'laugh',
      translation: 'смех',
      image: './img/laugh.jpg',
      audioSrc: './audio/laugh.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
  ],
  [
    {
      category: 'Vegetables',
      word: 'avocado',
      translation: 'авокадо',
      image: './img/avocado.jpg',
      audioSrc: './audio/avocado.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Vegetables',
      word: 'carrot',
      translation: 'морковь',
      image: './img/carrot.jpg',
      audioSrc: './audio/carrot.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Vegetables',
      word: 'onion',
      translation: 'лук',
      image: './img/onion.jpg',
      audioSrc: './audio/onion.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Vegetables',
      word: 'tomato',
      translation: 'томат',
      image: './img/tomato.jpg',
      audioSrc: './audio/tomato.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Vegetables',
      word: 'cabbage',
      translation: 'капуста',
      image: './img/cabbage.jpg',
      audioSrc: './audio/cabbage.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Vegetables',
      word: 'pumpkin',
      translation: 'тыква',
      image: './img/pumpkin.jpg',
      audioSrc: './audio/pumpkin.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Vegetables',
      word: 'eggplant',
      translation: 'баклажан',
      image: './img/eggplant.jpg',
      audioSrc: './audio/eggplant.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Vegetables',
      word: 'zucchini',
      translation: 'цукини',
      image: './img/zucchini.jpg',
      audioSrc: './audio/zucchini.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
  ],
  [
    {
      category: 'Fruits',
      word: 'orange',
      translation: 'апельсин',
      image: './img/orange.jpg',
      audioSrc: './audio/orange.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Fruits',
      word: 'grapes',
      translation: 'виноград',
      image: './img/grapes.jpg',
      audioSrc: './audio/grapes.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Fruits',
      word: 'banana',
      translation: 'банан',
      image: './img/banana.jpg',
      audioSrc: './audio/banana.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Fruits',
      word: 'pineapple',
      translation: 'ананас',
      image: './img/pineapple.jpg',
      audioSrc: './audio/pineapple.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Fruits',
      word: 'persimmon',
      translation: 'хурма',
      image: './img/persimmon.jpg',
      audioSrc: './audio/persimmon.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Fruits',
      word: 'mango',
      translation: 'манго',
      image: './img/mango.jpg',
      audioSrc: './audio/mango.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Fruits',
      word: 'apple',
      translation: 'яблоко',
      image: './img/apple.jpg',
      audioSrc: './audio/apple.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Fruits',
      word: 'pear',
      translation: 'груша',
      image: './img/pear.jpg',
      audioSrc: './audio/pear.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
  ],
  [
    {
      category: 'Nature',
      word: 'forest',
      translation: 'лес',
      image: './img/forest.jpg',
      audioSrc: './audio/forest.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Nature',
      word: 'beach',
      translation: 'пляж',
      image: './img/beach.jpg',
      audioSrc: './audio/beach.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Nature',
      word: 'snow',
      translation: 'снег',
      image: './img/snow.jpg',
      audioSrc: './audio/snow.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Nature',
      word: 'desert',
      translation: 'пустыня',
      image: './img/desert.jpg',
      audioSrc: './audio/desert.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Nature',
      word: 'rainbow',
      translation: 'радуга',
      image: './img/rainbow.jpg',
      audioSrc: './audio/rainbow.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Nature',
      word: 'mountain',
      translation: 'гора',
      image: './img/mountain.jpg',
      audioSrc: './audio/mountain.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Nature',
      word: 'grass',
      translation: 'трава',
      image: './img/grass.jpeg',
      audioSrc: './audio/grass.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'Nature',
      word: 'cloud',
      translation: 'облако',
      image: './img/cloud.jpg',
      audioSrc: './audio/cloud.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
  ],
  [
    {
      category: 'City',
      word: 'road',
      translation: 'дорога',
      image: './img/road.jpg',
      audioSrc: './audio/road.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'City',
      word: 'building',
      translation: 'здание',
      image: './img/building.jpg',
      audioSrc: './audio/building.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'City',
      word: 'crossroad',
      translation: 'перекресток',
      image: './img/crossroad.jpg',
      audioSrc: './audio/crossroad.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'City',
      word: 'store',
      translation: 'магазин',
      image: './img/store.jpg',
      audioSrc: './audio/store.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'City',
      word: 'car',
      translation: 'машина',
      image: './img/car.jpg',
      audioSrc: './audio/car.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'City',
      word: 'bus',
      translation: 'автобус',
      image: './img/bus.jpg',
      audioSrc: './audio/bus.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'City',
      word: 'bench',
      translation: 'скамейка',
      image: './img/bench.jpg',
      audioSrc: './audio/bench.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
    {
      category: 'City',
      word: 'theatre',
      translation: 'театр',
      image: './img/theatre.jpg',
      audioSrc: './audio/theatre.mp3',
      trained: 0,
      correct: 0,
      errors: 0,
      '%': 0,
    },
  ],
  [
  ],
];

export {cards, cards1};
